# Generated by Django 6.0.7 on 2026-07-31

import django.contrib.gis.db.models.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Settlement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(choices=[('os_open_names', 'OS Open Names')], max_length=32)),
                ('source_id', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=150)),
                ('alternate_name', models.CharField(blank=True, max_length=150)),
                ('settlement_type', models.CharField(choices=[('city', 'City'), ('town', 'Town'), ('village', 'Village'), ('hamlet', 'Hamlet')], max_length=16)),
                ('country', models.CharField(choices=[('England', 'England'), ('Scotland', 'Scotland'), ('Wales', 'Wales'), ('Northern Ireland', 'Northern Ireland')], max_length=32)),
                ('location', django.contrib.gis.db.models.fields.PointField(srid=4326)),
                ('population', models.PositiveIntegerField(blank=True, null=True)),
                ('region', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='settlements', to='locations.region')),
            ],
            options={
                'ordering': ['name'],
                'indexes': [models.Index(fields=['settlement_type', 'name'], name='settlement_type_name_idx')],
                'constraints': [models.UniqueConstraint(fields=('source', 'source_id'), name='unique_settlement_source_id')],
            },
        ),
    ]
